import { Router, type RequestHandler } from "express";
import { OAuth2Client } from "google-auth-library";
import crypto from "node:crypto";
import { pool } from "@workspace/db";
const router=Router(); const google=new OAuth2Client(); const COOKIE="clashiq_session"; let ready:Promise<void>|null=null;
async function schema(){if(!ready) ready=(async()=>{await pool.query(`CREATE TABLE IF NOT EXISTS clashiq_users(id UUID PRIMARY KEY,google_sub TEXT UNIQUE NOT NULL,email TEXT NOT NULL,name TEXT,picture TEXT,player_tag TEXT,role TEXT NOT NULL DEFAULT 'user',premium_status TEXT NOT NULL DEFAULT 'free',premium_until TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);await pool.query(`CREATE TABLE IF NOT EXISTS clashiq_sessions(id TEXT PRIMARY KEY,user_id UUID NOT NULL REFERENCES clashiq_users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);})();return ready;}
async function user(req:any){await schema();const sid=req.cookies?.[COOKIE];if(!sid)return null;const r=await pool.query("SELECT u.* FROM clashiq_users u JOIN clashiq_sessions s ON s.user_id=u.id WHERE s.id=$1 AND s.expires_at>NOW()",[sid]);return r.rows[0]??null;}
export const requireAuth:RequestHandler=async(req,res,next)=>{try{const u=await user(req);if(!u)return res.status(401).json({error:"Not authenticated"});(req as any).clashUser=u;next();}catch{res.status(500).json({error:"Authentication unavailable"});}};
export const requireAdmin:RequestHandler=async(req,res,next)=>{await requireAuth(req,res,()=>{if((req as any).clashUser.role!=="admin")return res.status(403).json({error:"Admin only"});next();});};
router.get("/auth/config",(_req,res)=>res.json({clientId:process.env.GOOGLE_CLIENT_ID??""}));
router.post("/auth/google",async(req,res)=>{try{await schema();const credential=String(req.body?.credential??"");const clientId=process.env.GOOGLE_CLIENT_ID;if(!clientId)return res.status(503).json({error:"Google login is not configured"});const ticket=await google.verifyIdToken({idToken:credential,audience:clientId});const p=ticket.getPayload();if(!p?.sub||!p.email)return res.status(401).json({error:"Invalid Google account"});let r=await pool.query("SELECT * FROM clashiq_users WHERE google_sub=$1",[p.sub]);let u=r.rows[0];if(!u){const first=(await pool.query("SELECT COUNT(*)::int AS n FROM clashiq_users")).rows[0].n===0;u=(await pool.query("INSERT INTO clashiq_users(id,google_sub,email,name,picture,role,premium_status) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *",[crypto.randomUUID(),p.sub,p.email,p.name??null,p.picture??null,first?"admin":"user",first?"lifetime":"free"])).rows[0];}else{u=(await pool.query("UPDATE clashiq_users SET email=$2,name=$3,picture=$4,updated_at=NOW() WHERE google_sub=$1 RETURNING *",[p.sub,p.email,p.name??null,p.picture??null])).rows[0];}const sid=crypto.randomBytes(32).toString("hex");await pool.query("INSERT INTO clashiq_sessions(id,user_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 days')",[sid,u.id]);res.cookie(COOKIE,sid,{httpOnly:true,sameSite:"lax",secure:process.env.NODE_ENV==="production",maxAge:2592000000,path:"/"});res.json({user:u});}catch(e){console.error(e);res.status(401).json({error:"Google authentication failed"});}});
router.get("/auth/me",async(req,res)=>{const u=await user(req);if(!u)return res.status(401).json({error:"Not authenticated"});res.json({user:u});});
router.post("/auth/logout",async(req,res)=>{await schema();const sid=req.cookies?.[COOKIE];if(sid)await pool.query("DELETE FROM clashiq_sessions WHERE id=$1",[sid]);res.clearCookie(COOKIE,{path:"/"});res.json({ok:true});});
router.post("/auth/player",requireAuth,async(req,res)=>{const tag=String(req.body?.playerTag??"").trim().toUpperCase();if(!/^#[A-Z0-9]{5,15}$/.test(tag))return res.status(400).json({error:"Invalid Player Tag"});const u=(req as any).clashUser;await pool.query("UPDATE clashiq_users SET player_tag=$2,updated_at=NOW() WHERE id=$1",[u.id,tag]);res.json({playerTag:tag});});
router.get("/auth/admin/users",requireAdmin,async(_req,res)=>res.json({users:(await pool.query("SELECT id,email,name,picture,player_tag,role,premium_status,premium_until,created_at FROM clashiq_users ORDER BY created_at")).rows}));
router.post("/auth/admin/users/:id/lifetime",requireAdmin,async(req,res)=>{const r=await pool.query("UPDATE clashiq_users SET premium_status='lifetime',premium_until=NULL WHERE id=$1 RETURNING id,email,premium_status",[req.params.id]);if(!r.rowCount)return res.status(404).json({error:"User not found"});res.json({user:r.rows[0]});});
router.post("/auth/admin/users/:id/free",requireAdmin,async(req,res)=>{const r=await pool.query("UPDATE clashiq_users SET premium_status='free',premium_until=NULL WHERE id=$1 RETURNING id,email,premium_status",[req.params.id]);if(!r.rowCount)return res.status(404).json({error:"User not found"});res.json({user:r.rows[0]});});
export default router;