import { Router, type IRouter } from "express";
import legacyRouter from "./clash-legacy";
import dashboardRouter from "./clash-dashboard";
import archiveRouter from "./clash-archive";
import playerRouter from "./clash-player";
import trendsRouter from "./clash-trends";
import warPlannerAssignmentsRouter from "./clash-war-planner-assignments";
const router: IRouter = Router();
router.use(legacyRouter); router.use(dashboardRouter); router.use(archiveRouter); router.use(playerRouter); router.use(trendsRouter); router.use(warPlannerAssignmentsRouter);
export default router;