import { useEffect, useState } from 'react';
import { AppSidebar } from '@/components/app-sidebar';
import {
  clearWarChatMessages,
  getWarChatMessages,
  removeWarChatMessage,
  type WarChatMessage,
} from '@/lib/war-chat';
import { Copy, MessageSquareText, Trash2, Users, Swords, BrainCircuit, Trophy } from 'lucide-react';

const sourceMeta: Record<WarChatMessage['source'], { label: string; icon: typeof Swords; className: string }> = {
  'war-planner': { label: 'War Planner', icon: Swords, className: 'text-amber-300' },
  'war-log': { label: 'War Log', icon: Trophy, className: 'text-emerald-300' },
  'ai-coach': { label: 'AI Coach', icon: BrainCircuit, className: 'text-blue-300' },
  manual: { label: 'Manual', icon: Users, className: 'text-white/60' },
};

export default function WarChatPage() {
  const [messages, setMessages] = useState<WarChatMessage[]>([]);
  const [copied, setCopied] = useState<string | null>(null);

  const refresh = () => setMessages(getWarChatMessages());

  useEffect(() => {
    refresh();
    const handler = () => refresh();
    window.addEventListener('clashiq-war-chat-changed', handler);
    return () => window.removeEventListener('clashiq-war-chat-changed', handler);
  }, []);

  const copy = async (message: WarChatMessage) => {
    try {
      await navigator.clipboard.writeText(message.body);
      setCopied(message.id);
      window.setTimeout(() => setCopied(null), 1800);
    } catch {
      setCopied(null);
    }
  };

  return (
    <div className="min-h-[100dvh] bg-[#02070d] text-white">
      <div className="flex min-h-[100dvh]">
        <AppSidebar />
        <main className="min-w-0 flex-1">
          <div className="mx-auto max-w-[1100px] space-y-5 p-4 md:p-8">
            <section className="relative overflow-hidden rounded-3xl border border-[#f4c542]/20 bg-[#06111b] p-6 shadow-[0_20px_80px_rgba(0,0,0,.35)] md:p-8">
              <div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_85%_10%,rgba(244,197,66,.14),transparent_35%),radial-gradient(circle_at_10%_90%,rgba(45,140,255,.10),transparent_35%)]" />
              <div className="relative">
                <div className="flex items-center gap-3">
                  <div className="grid size-12 place-items-center rounded-2xl border border-amber-400/25 bg-amber-400/10">
                    <MessageSquareText className="size-6 text-amber-300" />
                  </div>
                  <div>
                    <p className="text-[9px] font-black uppercase tracking-[.24em] text-amber-300">ClashIQ Communications</p>
                    <h1 className="mt-1 text-3xl font-black tracking-tight md:text-4xl">War Chat</h1>
                  </div>
                </div>
                <p className="mt-4 max-w-2xl text-sm leading-6 text-white/50">
                  One place for the messages generated by War Planner, War Log and AI Coach. Copy a message and publish it wherever your clan communicates.
                </p>
              </div>
            </section>

            <div className="flex items-center justify-between gap-3">
              <div>
                <p className="text-[9px] font-black uppercase tracking-[.2em] text-white/30">Published messages</p>
                <p className="mt-1 text-sm text-white/50">{messages.length} saved on this device</p>
              </div>
              {messages.length > 0 && (
                <button
                  type="button"
                  onClick={() => {
                    clearWarChatMessages();
                    refresh();
                  }}
                  className="inline-flex items-center gap-2 rounded-xl border border-red-400/15 bg-red-400/[.04] px-3 py-2 text-xs font-bold text-red-300 hover:bg-red-400/[.08]"
                >
                  <Trash2 className="size-3.5" />
                  Clear chat
                </button>
              )}
            </div>

            {messages.length === 0 ? (
              <section className="grid place-items-center rounded-3xl border border-white/[.07] bg-[#06111b]/80 px-6 py-16 text-center">
                <MessageSquareText className="size-10 text-amber-300/20" />
                <h2 className="mt-4 text-lg font-black">No war messages yet</h2>
                <p className="mt-2 max-w-md text-sm leading-6 text-white/35">
                  Generate a message in War Planner or AI Coach, then press Publish to War Chat. War Log results can be published here too.
                </p>
              </section>
            ) : (
              <section className="space-y-3">
                {messages.map(message => {
                  const meta = sourceMeta[message.source];
                  const Icon = meta.icon;
                  return (
                    <article key={message.id} className="overflow-hidden rounded-2xl border border-white/[.07] bg-[#06111b]/90">
                      <header className="flex items-center gap-3 border-b border-white/[.06] px-4 py-3">
                        <Icon className={`size-4 ${meta.className}`} />
                        <div className="min-w-0 flex-1">
                          <p className="text-xs font-black">{message.title}</p>
                          <p className="mt-0.5 text-[9px] uppercase tracking-wider text-white/30">
                            {meta.label} · {new Date(message.createdAt).toLocaleString()}
                          </p>
                        </div>
                        <button
                          type="button"
                          onClick={() => void copy(message)}
                          className="inline-flex items-center gap-2 rounded-lg border border-white/10 bg-white/[.04] px-3 py-2 text-[10px] font-black uppercase tracking-wider text-white/70 hover:bg-white/[.08]"
                        >
                          <Copy className="size-3.5" />
                          {copied === message.id ? 'Copied' : 'Copy'}
                        </button>
                        <button
                          type="button"
                          onClick={() => removeWarChatMessage(message.id)}
                          className="grid size-8 place-items-center rounded-lg text-white/30 hover:bg-red-400/[.08] hover:text-red-300"
                          aria-label="Delete message"
                        >
                          <Trash2 className="size-3.5" />
                        </button>
                      </header>
                      <pre className="whitespace-pre-wrap p-4 text-sm leading-6 text-white/75">{message.body}</pre>
                    </article>
                  );
                })}
              </section>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}
